name: dart_lessons
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  faker: ^2.1.0
  dartz: ^0.10.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  injectable_generator: ^2.6.2
  build_runner: any
